kind: pipeline
type: kubernetes
steps:
  # - name: test
  #   image: node:alpine
  #   commands:
  #     - cd dmScreen
  #     - npm install
  #     - npm test
  - name: docker
    image: plugins/kaniko
    environment:
      PLUGIN_USERNAME:
        from_secret: docker_username
      PLUGIN_PASSWORD:
        from_secret: docker_password
      PLUGIN_TAGS: dmScreen
      PLUGIN_REPO: munhunger/dnd
      PLUGIN_DOCKERFILE: dmScreen/Dockerfile
    settings:
      context: dmScreen

    # settings:
    #   context: dmScreen
    #   dockerfile: dmScreen/Dockerfile
    #   build_args:
    #     - "--force"
