kind: pipeline
type: kubernetes
steps:
  - name: test
    image: node:alpine
    commands:
      - cd dmScreen
      - npm install
      - npm test
  - name: audit
    image: node:alpine
    commands:
      - cd dmScreen
      - npm audit
      - npm audit fix
  - name: git
    image: alpine/git
    environment:
      GIT_AUTHOR_EMAIL: drone@munhunger.com
      GIT_AUTHOR_name: drone
      GIT_COMMITTER_NAME: drone
      TOKEN:
        from_secret: git_token
    commands:
      - git diff .
      - git add .
      - git commit -m "dependency update"
      - git status
      - git log -n 2
      - printenv
      - echo $DRONE_SOURCE_BRANCH
      - git remote rm origin
      - git remote add origin https://drone:$TOKEN@github.com/munhunger/dnd.git
      - git push --set-upstream origin $DRONE_SOURCE_BRANCH
  - name: docker
    image: plugins/kaniko
    environment:
      PLUGIN_USERNAME:
        from_secret: docker_username
      PLUGIN_PASSWORD:
        from_secret: docker_password
      PLUGIN_TAGS: dmScreen
      PLUGIN_REPO: munhunger/dnd
      PLUGIN_DOCKERFILE: dmScreen/Dockerfile
    settings:
      context: dmScreen
