apiVersion: v1
kind: Namespace
metadata:
  name: dm-screen
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
  namespace: dm-screen
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: node
    spec: # pod spec
      containers:
        - name: node
          image: munhunger/dnd:dmScreen
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: dm-screen
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: mongo
    spec: # pod spec
      volumes:
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pvc
        - name: podinfo
          downwardAPI:
            items:
              - path: name
                fieldRef:
                  fieldPath: metadata.name
      containers:
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: '/data/db'
              name: mongo-pv
            - mountPath: '/etc/podinfo'
              name: podinfo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: dm-screen
  labels:
    app: mongo-express
spec:
  replicas: 1
  strategy:
    type: Recreate #it is locking the db so we need downtime
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: mongo-express
    spec: # pod spec
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: dm-screen
  labels:
    type: local
spec:
  storageClassName: 'manual'
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/dm-screen'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: dm-screen
spec:
  storageClassName: 'manual'
  accessModes:
    - 'ReadWriteOnce'
  resources:
    requests:
      storage: 20Mi

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: dm-screen
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      name: mongo
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: dm-screen
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 31012
      targetPort: 8081
      name: mongo-express
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: dm-screen
spec:
  selector:
    app: node
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 31011
      targetPort: 3000
      name: node
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dm-screen-ingress
  namespace: dm-screen
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - dnd.munhunger.com
      secretName: dnd-tls
  rules:
    - host: dnd.munhunger.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: node
                port:
                  number: 3000
