apiVersion: apps/v1
kind: Deployment
metadata:
  name: dm-screen
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dm-screen
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: dm-screen
    spec:     # pod spec
      containers:
      - name: dm-screen
        image: munhunger/dnd:dmScreen
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: dnd-load-balancer
spec:
  selector:
    app: dm-screen
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 31011
    targetPort: 3000
  type: LoadBalancer
